# Generated by Django 5.2.11 on 2026-03-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fio',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Администратор', 'Администратор'), ('Оператор', 'Оператор'), ('Мастер', 'Мастер'), ('Менеджер', 'Менеджер'), ('Заказчик', 'Заказчик')], max_length=20),
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
