# Generated by Django 5.2.11 on 2026-03-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_fio_alter_user_groups_alter_user_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Администратор', 'Администратор'), ('Оператор', 'Оператор'), ('Мастер', 'Мастер'), ('Менеджер', 'Менеджер'), ('Менеджер по качеству', 'Менеджер по качеству'), ('Заказчик', 'Заказчик')], max_length=30),
        ),
    ]
