# Generated by Django 5.2.11 on 2026-03-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentID', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'db_table': 'requests_comment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('requestID', models.AutoField(primary_key=True, serialize=False)),
                ('startDate', models.DateField()),
                ('homeTechType', models.CharField(choices=[('Холодильник', 'Холодильник'), ('Стиральная машина', 'Стиральная машина'), ('Фен', 'Фен'), ('Тостер', 'Тостер'), ('Мультиварка', 'Мультиварка'), ('Плита', 'Плита'), ('Микроволновка', 'Микроволновка'), ('Другое', 'Другое')], max_length=50)),
                ('homeTechModel', models.CharField(max_length=100)),
                ('problemDescryption', models.TextField()),
                ('requestStatus', models.CharField(choices=[('Новая заявка', 'Новая заявка'), ('В процессе ремонта', 'В процессе ремонта'), ('Готова к выдаче', 'Готова к выдаче'), ('Выполнена', 'Выполнена'), ('Отменена', 'Отменена')], default='Новая заявка', max_length=50)),
                ('completionDate', models.DateField(blank=True, null=True)),
                ('repairParts', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'db_table': 'requests_request',
                'ordering': ['-startDate'],
            },
        ),
    ]
