# Generated by Django 5.2.11 on 2026-03-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='homeTechType',
            field=models.CharField(choices=[('Холодильник', 'Холодильник'), ('Стиральная машина', 'Стиральная машина'), ('Фен', 'Фен'), ('Тостер', 'Тостер'), ('Мультиварка', 'Мультиварка')], max_length=50),
        ),
        migrations.AlterField(
            model_name='request',
            name='requestStatus',
            field=models.CharField(choices=[('Новая заявка', 'Новая заявка'), ('В процессе ремонта', 'В процессе ремонта'), ('Готова к выдаче', 'Готова к выдаче'), ('Выполнена', 'Выполнена')], default='Новая заявка', max_length=50),
        ),
        migrations.AlterModelTable(
            name='comment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='request',
            table=None,
        ),
    ]
