# Generated by Django 5.2.11 on 2026-03-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_alter_request_hometechtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='deadline_extended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='homeTechType',
            field=models.CharField(choices=[('Холодильник', 'Холодильник'), ('Стиральная машина', 'Стиральная машина'), ('Фен', 'Фен'), ('Тостер', 'Тостер'), ('Мультиварка', 'Мультиварка'), ('Плита', 'Плита'), ('Микроволновка', 'Микроволновка')], max_length=50),
        ),
        migrations.AlterField(
            model_name='request',
            name='requestStatus',
            field=models.CharField(choices=[('Новая заявка', 'Новая заявка'), ('В процессе ремонта', 'В процессе ремонта'), ('Готова к выдаче', 'Готова к выдаче'), ('Выполнена', 'Выполнена'), ('Просрочена', 'Просрочена')], default='Новая заявка', max_length=50),
        ),
    ]
