# Generated by Django 5.2.11 on 2026-03-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_request_deadline_extended_alter_request_hometechtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_type',
            field=models.CharField(choices=[('internal', 'Внутренний'), ('client', 'Для клиента')], default='internal', max_length=20),
        ),
        migrations.AddField(
            model_name='request',
            name='deadline_extended_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='extension_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='requestStatus',
            field=models.CharField(choices=[('Новая заявка', 'Новая заявка'), ('В процессе ремонта', 'В процессе ремонта'), ('Готова к выдаче', 'Готова к выдаче')], default='Новая заявка', max_length=50),
        ),
    ]
